version: "3.8"

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl-panel
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_URL=http://localhost
      - DB_CONNECTION=sqlite
    volumes:
      - ./data:/var/lib/pterodactyl
